				SECTION	TEXT
			MOD_ABS:	BEGIN
				PUBLIC	SAIDA_ABS
				INPUT	ENTRADA_ABS
				LOAD	ENTRADA_ABS
				JMPP	FIM_ABS
				JMPZ	FIM_ABS
CASO_NEGATIVO:	MULT	MINUS_ONE
FIM_ABS:		STORE SAIDA_ABS
				STOP

SECTION	DATA
MINUS_ONE:	CONST -1
ENTRADA_ABS:	SPACE
SAIDA_ABS:	SPACE
END